dv_bins = 10;
ax = []
which_switch = '';
max_t       = 1.5;
t0s         = .1:.025:max_t-lag;

res_on = dyn_fr_dv_map(excellid, 't0s', t0s, ...
        'data',data, 'model', model, 'lag', lag, ...
        'alignment', 'stimstart',...
        'krn_width', krn_width, 'krn_type', krn_type,...
        'norm_type', norm_type,'shuffle_trials',0,...
        'n_dv_bins',dv_bins,'end_mask_s',end_mask_s,...
        'demean_frates',demean_frates,'zscore_frates',zscore_frates,...
        'which_switch',which_switch, 'shuffle_trials', do_shuffle_trials, ...
        'shuffle_switches', do_shuffle_switches,...
        'min_switch_t',min_switch_t, 'max_switch_t',max_switch_t,...
        'shuffle_trials_fixing_choice',do_shuffle_fixing_choice,...
        'do_svd',0)
  
figure(1); clf

ax(1) = subplot(131);
fgta_line_plot(res_on,'colorbar_location','','ax',ax(1),...
    'plot_field','fgta_resid','dvlims',dvlims,'goodtind',~badtind)
%title('rank 1 approximation','interpreter','latex')
xlabel('time from stim on (s)')
ylabel('\Delta FR')
axis(ax(1), 'tight')
%ylim(get(ax_r,'ylim'))
drawnow
pos1 = get(ax(1),'position');
  %%
  
  


%t0s         = -1.5:0.025:-0.1-lag;  
t0s = sort(-t0s);

res_off = dyn_fr_dv_map(excellid, 't0s', t0s, ...
        'data',data, 'model', model, 'lag', lag, ...
        'alignment', 'stimend',...
        'krn_width', krn_width, 'krn_type', krn_type,...
        'norm_type', norm_type,'shuffle_trials',0,...
        'n_dv_bins',dv_bins,'end_mask_s',end_mask_s,...
        'demean_frates',demean_frates,'zscore_frates',zscore_frates,...
        'which_switch',which_switch, 'shuffle_trials', do_shuffle_trials, ...
        'shuffle_switches', do_shuffle_switches,...
        'min_switch_t',min_switch_t, 'max_switch_t',max_switch_t,...
        'shuffle_trials_fixing_choice',do_shuffle_fixing_choice,...
        'do_svd',0)
  dvlims = []

ax(2) = subplot(132);
fgta_line_plot(res_off,'colorbar_location','','ax',ax(2),...
    'plot_field','fgta_resid','dvlims',dvlims,'goodtind',~badtind)
ylabel('\Delta FR')
axis(ax(2), 'tight')
%ylim(get(ax_r,'ylim'))
drawnow
pos1 = get(ax(2),'position');

linkaxes(ax,'y')

%%
lw = 1
ax_ = subplot(133)
ra_field = 'fga_resid_tmn';
fgta_plot_tuning(res_on,'plot_field',ra_field, ...
    'errorbar_field','','ax',ax_,'dvlims',dvlims, ...
    'linewidth', lw, 'linecolor', 'k')
hold on
fgta_plot_tuning(res_off,'plot_field',ra_field, ...
    'errorbar_field','','ax',ax_,'dvlims',dvlims, ...
    'linewidth', lw, 'linecolor', 'r')
legend('on','off')